//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Inputs/PlayerInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputs"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""fd37c87a-131b-4e1a-9819-6652489e1816"",
            ""actions"": [
                {
                    ""name"": ""LeftControllerPrimaryButtonClicked"",
                    ""type"": ""Button"",
                    ""id"": ""4b63758e-8187-40e9-87f3-121b4a6fa154"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightControllerPrimaryButtonClicked"",
                    ""type"": ""Button"",
                    ""id"": ""76e55749-1083-469b-ab72-898bb22b6d4e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c4b93150-407c-4675-9ec5-7214aa5b56e7"",
                    ""path"": ""<XRController>{LeftHand}/{PrimaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftControllerPrimaryButtonClicked"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6707a644-1b62-49ac-9773-39ba5e752ebb"",
                    ""path"": ""<XRController>{RightHand}/{PrimaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightControllerPrimaryButtonClicked"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_LeftControllerPrimaryButtonClicked = m_Player.FindAction("LeftControllerPrimaryButtonClicked", throwIfNotFound: true);
        m_Player_RightControllerPrimaryButtonClicked = m_Player.FindAction("RightControllerPrimaryButtonClicked", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_LeftControllerPrimaryButtonClicked;
    private readonly InputAction m_Player_RightControllerPrimaryButtonClicked;
    public struct PlayerActions
    {
        private @PlayerInputs m_Wrapper;
        public PlayerActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @LeftControllerPrimaryButtonClicked => m_Wrapper.m_Player_LeftControllerPrimaryButtonClicked;
        public InputAction @RightControllerPrimaryButtonClicked => m_Wrapper.m_Player_RightControllerPrimaryButtonClicked;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @LeftControllerPrimaryButtonClicked.started += instance.OnLeftControllerPrimaryButtonClicked;
            @LeftControllerPrimaryButtonClicked.performed += instance.OnLeftControllerPrimaryButtonClicked;
            @LeftControllerPrimaryButtonClicked.canceled += instance.OnLeftControllerPrimaryButtonClicked;
            @RightControllerPrimaryButtonClicked.started += instance.OnRightControllerPrimaryButtonClicked;
            @RightControllerPrimaryButtonClicked.performed += instance.OnRightControllerPrimaryButtonClicked;
            @RightControllerPrimaryButtonClicked.canceled += instance.OnRightControllerPrimaryButtonClicked;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @LeftControllerPrimaryButtonClicked.started -= instance.OnLeftControllerPrimaryButtonClicked;
            @LeftControllerPrimaryButtonClicked.performed -= instance.OnLeftControllerPrimaryButtonClicked;
            @LeftControllerPrimaryButtonClicked.canceled -= instance.OnLeftControllerPrimaryButtonClicked;
            @RightControllerPrimaryButtonClicked.started -= instance.OnRightControllerPrimaryButtonClicked;
            @RightControllerPrimaryButtonClicked.performed -= instance.OnRightControllerPrimaryButtonClicked;
            @RightControllerPrimaryButtonClicked.canceled -= instance.OnRightControllerPrimaryButtonClicked;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnLeftControllerPrimaryButtonClicked(InputAction.CallbackContext context);
        void OnRightControllerPrimaryButtonClicked(InputAction.CallbackContext context);
    }
}
