//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Inputs/PlayerInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputs"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""fd37c87a-131b-4e1a-9819-6652489e1816"",
            ""actions"": [
                {
                    ""name"": ""LeftControllerPrimaryButtonClicked"",
                    ""type"": ""Button"",
                    ""id"": ""4b63758e-8187-40e9-87f3-121b4a6fa154"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightControllerPrimaryButtonClicked"",
                    ""type"": ""Button"",
                    ""id"": ""76e55749-1083-469b-ab72-898bb22b6d4e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c4b93150-407c-4675-9ec5-7214aa5b56e7"",
                    ""path"": ""<XRController>{LeftHand}/{PrimaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftControllerPrimaryButtonClicked"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6707a644-1b62-49ac-9773-39ba5e752ebb"",
                    ""path"": ""<XRController>{RightHand}/{PrimaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightControllerPrimaryButtonClicked"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""FirstPersonPlayer"",
            ""id"": ""5f74ed1f-dc6b-4eaf-84b4-eb26d34307a2"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""cfc4bc6c-8626-4ee2-89da-b53bbd513d2d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""aa349ddf-ba04-422a-8328-db48de5c1ab7"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector WASD"",
                    ""id"": ""af007bd1-f24f-4809-95a6-eaa719fc1f60"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""624ba26d-1163-4690-8016-02dc0853e7a9"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3d27648e-10a8-41ad-b16e-a0d467b49f7b"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""80f9ee30-9c88-48bd-818a-ed4845bc3f95"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3eab8520-c827-4b2b-a56c-8cf3b4ef662f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""91aec3b7-bb37-4d3e-82e1-62e1b88648a9"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_LeftControllerPrimaryButtonClicked = m_Player.FindAction("LeftControllerPrimaryButtonClicked", throwIfNotFound: true);
        m_Player_RightControllerPrimaryButtonClicked = m_Player.FindAction("RightControllerPrimaryButtonClicked", throwIfNotFound: true);
        // FirstPersonPlayer
        m_FirstPersonPlayer = asset.FindActionMap("FirstPersonPlayer", throwIfNotFound: true);
        m_FirstPersonPlayer_Move = m_FirstPersonPlayer.FindAction("Move", throwIfNotFound: true);
        m_FirstPersonPlayer_Look = m_FirstPersonPlayer.FindAction("Look", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_LeftControllerPrimaryButtonClicked;
    private readonly InputAction m_Player_RightControllerPrimaryButtonClicked;
    public struct PlayerActions
    {
        private @PlayerInputs m_Wrapper;
        public PlayerActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @LeftControllerPrimaryButtonClicked => m_Wrapper.m_Player_LeftControllerPrimaryButtonClicked;
        public InputAction @RightControllerPrimaryButtonClicked => m_Wrapper.m_Player_RightControllerPrimaryButtonClicked;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @LeftControllerPrimaryButtonClicked.started += instance.OnLeftControllerPrimaryButtonClicked;
            @LeftControllerPrimaryButtonClicked.performed += instance.OnLeftControllerPrimaryButtonClicked;
            @LeftControllerPrimaryButtonClicked.canceled += instance.OnLeftControllerPrimaryButtonClicked;
            @RightControllerPrimaryButtonClicked.started += instance.OnRightControllerPrimaryButtonClicked;
            @RightControllerPrimaryButtonClicked.performed += instance.OnRightControllerPrimaryButtonClicked;
            @RightControllerPrimaryButtonClicked.canceled += instance.OnRightControllerPrimaryButtonClicked;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @LeftControllerPrimaryButtonClicked.started -= instance.OnLeftControllerPrimaryButtonClicked;
            @LeftControllerPrimaryButtonClicked.performed -= instance.OnLeftControllerPrimaryButtonClicked;
            @LeftControllerPrimaryButtonClicked.canceled -= instance.OnLeftControllerPrimaryButtonClicked;
            @RightControllerPrimaryButtonClicked.started -= instance.OnRightControllerPrimaryButtonClicked;
            @RightControllerPrimaryButtonClicked.performed -= instance.OnRightControllerPrimaryButtonClicked;
            @RightControllerPrimaryButtonClicked.canceled -= instance.OnRightControllerPrimaryButtonClicked;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // FirstPersonPlayer
    private readonly InputActionMap m_FirstPersonPlayer;
    private List<IFirstPersonPlayerActions> m_FirstPersonPlayerActionsCallbackInterfaces = new List<IFirstPersonPlayerActions>();
    private readonly InputAction m_FirstPersonPlayer_Move;
    private readonly InputAction m_FirstPersonPlayer_Look;
    public struct FirstPersonPlayerActions
    {
        private @PlayerInputs m_Wrapper;
        public FirstPersonPlayerActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_FirstPersonPlayer_Move;
        public InputAction @Look => m_Wrapper.m_FirstPersonPlayer_Look;
        public InputActionMap Get() { return m_Wrapper.m_FirstPersonPlayer; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FirstPersonPlayerActions set) { return set.Get(); }
        public void AddCallbacks(IFirstPersonPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_FirstPersonPlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_FirstPersonPlayerActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
        }

        private void UnregisterCallbacks(IFirstPersonPlayerActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
        }

        public void RemoveCallbacks(IFirstPersonPlayerActions instance)
        {
            if (m_Wrapper.m_FirstPersonPlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IFirstPersonPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_FirstPersonPlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_FirstPersonPlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public FirstPersonPlayerActions @FirstPersonPlayer => new FirstPersonPlayerActions(this);
    public interface IPlayerActions
    {
        void OnLeftControllerPrimaryButtonClicked(InputAction.CallbackContext context);
        void OnRightControllerPrimaryButtonClicked(InputAction.CallbackContext context);
    }
    public interface IFirstPersonPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
    }
}
